### ISSUE TITLE
Is this workflow still functional? I can't get it to work at all on Alfred 4, macOS Monterey

### ISSUE THREAD

**Issue by ghost** [rx2130/alfred-safari-history-search#1]
This Alfred workflow sounds really useful But I haven't been able to get it to work on Alfred 4, macOS Monterey on multiple occasions. See attached screenshot of its Alfred debugging info below (I'm a noob when its comes to web developer/coding tools so I don't know where to go from there) 

<img width="1107" alt="Safari History Search" src="https://user-images.githubusercontent.com/94086315/175220430-52d7eab7-c0d4-45a7-bb0c-8b4805ab31c7.png">

**Comment by rx2130** [comment]
I have been using a modified version on my local since Apple removed Python 2 in Mac 12.3 earlier this year. Just pushed the code and created a [release](https://github.com/rx2130/alfred-safari-history-search/releases/download/v1.1.0/Search.Safari.History.alfredworkflow). Can you try that?

**Comment by ghost** [comment]
Yes that's awesome it worked. Thanks.
